# Generated by Django 5.2.4 on 2025-08-16 11:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gerente", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "contacto",
                    models.CharField(
                        blank=True,
                        help_text="Ex: +258 XX XXX XXXX",
                        max_length=20,
                        null=True,
                        verbose_name="Contacto",
                    ),
                ),
                (
                    "endereco",
                    models.TextField(
                        blank=True,
                        help_text="Endereço completo do cliente",
                        null=True,
                        verbose_name="Endereço",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Cliente ativo no sistema",
                        verbose_name="Ativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracaoSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_empresa",
                    models.CharField(
                        default="ENGEN", max_length=100, verbose_name="Nome da Empresa"
                    ),
                ),
                (
                    "limite_senhas_aviso",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Quantidade mínima que gera aviso de poucas senhas",
                        verbose_name="Limite para Aviso de Senhas",
                    ),
                ),
                (
                    "moeda",
                    models.CharField(default="MT", max_length=10, verbose_name="Moeda"),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração do Sistema",
                "verbose_name_plural": "Configurações do Sistema",
            },
        ),
        migrations.AlterModelOptions(
            name="funcionario",
            options={
                "ordering": ["-data_criacao"],
                "verbose_name": "Funcionário",
                "verbose_name_plural": "Funcionários",
            },
        ),
        migrations.RemoveField(
            model_name="funcionario",
            name="user",
        ),
        migrations.AddField(
            model_name="funcionario",
            name="ativo",
            field=models.BooleanField(
                default=True,
                help_text="Funcionário ativo no sistema",
                verbose_name="Ativo",
            ),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="data_atualizacao",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Última Atualização"
            ),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="contacto",
            field=models.CharField(
                blank=True,
                help_text="Ex: +258 XX XXX XXXX",
                max_length=20,
                null=True,
                verbose_name="Contacto",
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="data_criacao",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de Criação"
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="morada",
            field=models.TextField(
                blank=True,
                help_text="Endereço completo",
                null=True,
                verbose_name="Morada",
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
        migrations.CreateModel(
            name="Requisicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor em Meticais",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor (MT)",
                    ),
                ),
                (
                    "senhas",
                    models.PositiveIntegerField(
                        help_text="Quantidade total de senhas para esta requisição",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantidade de Senhas",
                    ),
                ),
                (
                    "senhas_restantes",
                    models.PositiveIntegerField(
                        help_text="Quantidade de senhas ainda disponíveis",
                        verbose_name="Senhas Restantes",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        help_text="Observações adicionais sobre a requisição",
                        null=True,
                        verbose_name="Observações",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "data_conclusao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Conclusão"
                    ),
                ),
                (
                    "ativa",
                    models.BooleanField(
                        default=True,
                        help_text="Requisição ativa no sistema",
                        verbose_name="Ativa",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisicoes",
                        to="gerente.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "funcionario_responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requisicoes_responsavel",
                        to="gerente.funcionario",
                        verbose_name="Funcionário Responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requisição",
                "verbose_name_plural": "Requisições",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoSenha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.IntegerField(
                        help_text="Quantidade de senhas (positivo = adicionado, negativo = usado)",
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        help_text="Motivo da alteração",
                        max_length=200,
                        verbose_name="Motivo",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data"),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gerente.funcionario",
                        verbose_name="Funcionário",
                    ),
                ),
                (
                    "requisicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_senhas",
                        to="gerente.requisicao",
                        verbose_name="Requisição",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Senha",
                "verbose_name_plural": "Histórico de Senhas",
                "ordering": ["-data_criacao"],
            },
        ),
    ]
