# Generated by Django 5.2.4 on 2025-08-17 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gerente", "0002_cliente_configuracaosistema_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Senha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Código da Senha"
                    ),
                ),
                ("usada", models.BooleanField(default=False)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="senhas",
                        to="gerente.cliente",
                    ),
                ),
                (
                    "requisicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lista_senhas",
                        to="gerente.requisicao",
                    ),
                ),
            ],
        ),
    ]
