# Generated by Django 5.2.4 on 2025-08-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gerente", "0003_senha"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="senha_visivel",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Senha Original"
            ),
        ),
    ]
