# Generated by Django 5.2.4 on 2025-08-18 20:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gerente", "0004_funcionario_senha_visivel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConfiguracaoSistema",
        ),
        migrations.AlterModelOptions(
            name="cliente",
            options={},
        ),
        migrations.AlterModelOptions(
            name="funcionario",
            options={},
        ),
        migrations.AlterModelOptions(
            name="requisicao",
            options={},
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="ativo",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="contacto",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="data_atualizacao",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="data_criacao",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="endereco",
        ),
        migrations.RemoveField(
            model_name="funcionario",
            name="ativo",
        ),
        migrations.RemoveField(
            model_name="funcionario",
            name="contacto",
        ),
        migrations.RemoveField(
            model_name="funcionario",
            name="data_atualizacao",
        ),
        migrations.RemoveField(
            model_name="funcionario",
            name="data_criacao",
        ),
        migrations.RemoveField(
            model_name="funcionario",
            name="morada",
        ),
        migrations.RemoveField(
            model_name="funcionario",
            name="password",
        ),
        migrations.RemoveField(
            model_name="funcionario",
            name="senha_visivel",
        ),
        migrations.RemoveField(
            model_name="requisicao",
            name="data_atualizacao",
        ),
        migrations.RemoveField(
            model_name="requisicao",
            name="observacoes",
        ),
        migrations.AddField(
            model_name="funcionario",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nome",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="nome",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="requisicao",
            name="ativa",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="requisicao",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requisicoes",
                to="gerente.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="requisicao",
            name="data_conclusao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="requisicao",
            name="data_criacao",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="requisicao",
            name="funcionario_responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gerente.funcionario",
            ),
        ),
        migrations.AlterField(
            model_name="requisicao",
            name="senhas",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="requisicao",
            name="senhas_restantes",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="requisicao",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="senha",
            name="codigo",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name="HistoricoSenha",
        ),
    ]
