# Generated by Django 5.2.4 on 2025-08-18 20:50

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gerente", "0005_delete_configuracaosistema_alter_cliente_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="contacto",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="data_criacao",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 8, 18, 20, 50, 34, 420888, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cliente",
            name="endereco",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="contacto",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="data_criacao",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="funcionario",
            name="morada",
            field=models.TextField(blank=True, null=True),
        ),
    ]
