# Generated by Django 5.2.4 on 2025-08-20 21:30

import django.core.validators
import django.db.models.deletion
import gerente.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gerente", "0006_cliente_contacto_cliente_data_criacao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequisicaoSaldo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        default=gerente.models.gerar_codigo,
                        editable=False,
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("ativa", models.BooleanField(default=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisicoes_saldo",
                        to="gerente.cliente",
                    ),
                ),
                (
                    "funcionario_responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gerente.funcionario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequisicaoSenhas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "senhas",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_conclusao", models.DateTimeField(blank=True, null=True)),
                ("ativa", models.BooleanField(default=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisicoes",
                        to="gerente.cliente",
                    ),
                ),
                (
                    "funcionario_responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gerente.funcionario",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="senha",
            name="requisicao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lista_senhas",
                to="gerente.requisicaosenhas",
            ),
        ),
        migrations.DeleteModel(
            name="Requisicao",
        ),
    ]
