# Generated by Django 5.2.4 on 2025-08-20 22:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gerente", "0007_requisicaosaldo_requisicaosenhas_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("descricao", models.CharField(blank=True, max_length=200)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "requisicao_saldo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentos",
                        to="gerente.requisicaosaldo",
                    ),
                ),
            ],
        ),
    ]
