# Generated by Django 5.2.4 on 2025-08-23 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
        ("gerente", "0010_alter_funcionario_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientes",
                to="empresas.empresa",
            ),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funcionarios",
                to="empresas.empresa",
            ),
        ),
        migrations.AddField(
            model_name="movimento",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimentos",
                to="empresas.empresa",
            ),
        ),
        migrations.AddField(
            model_name="requisicaosaldo",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requisicoes_saldo",
                to="empresas.empresa",
            ),
        ),
        migrations.AddField(
            model_name="requisicaosenhas",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requisicoes_senhas",
                to="empresas.empresa",
            ),
        ),
        migrations.AddField(
            model_name="senha",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="senhas",
                to="empresas.empresa",
            ),
        ),
    ]
