# Generated by Django 5.2.4 on 2025-08-23 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
        ("gerente", "0011_cliente_empresa_funcionario_empresa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimento",
            name="funcionario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimentos_realizados",
                to="gerente.funcionario",
            ),
        ),
        migrations.AddField(
            model_name="senha",
            name="data_uso",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="senha",
            name="funcionario_uso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="senhas_escaneadas",
                to="gerente.funcionario",
            ),
        ),
        migrations.CreateModel(
            name="LogSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_acao",
                    models.CharField(
                        choices=[
                            ("SENHA_ESCANEADA", "Senha Escaneada"),
                            ("DEBITO_SALDO", "Débito de Saldo"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField()),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="gerente.funcionario",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_hora"],
            },
        ),
    ]
