# Generated by Django 5.2.4 on 2025-08-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gerente", "0013_requisicaosaldo_forma_pagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisicaosenhas",
            name="banco",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nome do Banco"
            ),
        ),
        migrations.AddField(
            model_name="requisicaosenhas",
            name="forma_pagamento",
            field=models.CharField(
                choices=[
                    ("transferencia", "Transferência Bancária"),
                    ("cash", "Dinheiro (Cash)"),
                    ("pos", "POS (Cartão)"),
                ],
                default="cash",
                max_length=20,
                verbose_name="Forma de Pagamento",
            ),
        ),
    ]
