# Generated by Django 5.2.4 on 2025-08-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gerente", "0014_requisicaosenhas_banco_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisicaosaldo",
            name="banco",
            field=models.CharField(
                blank=True,
                help_text="Obrigatório apenas para transferência bancária",
                max_length=100,
                null=True,
                verbose_name="Nome do Banco",
            ),
        ),
    ]
