# Generated by Django 5.2.4 on 2025-08-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gerente", "0015_requisicaosaldo_banco"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimento",
            name="tipo_combustivel",
            field=models.CharField(
                blank=True,
                choices=[("gasolina", "Gasolina"), ("diesel", "Diesel")],
                max_length=10,
                null=True,
            ),
        ),
    ]
