# Generated by Django 5.2.4 on 2025-08-25 06:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
        ("gerente", "0016_movimento_tipo_combustivel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fecho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fechos",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fecho",
                "verbose_name_plural": "Fechos",
                "ordering": ["-data"],
            },
        ),
        migrations.AddField(
            model_name="movimento",
            name="fecho",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimentos",
                to="gerente.fecho",
            ),
        ),
        migrations.AddField(
            model_name="requisicaosaldo",
            name="fecho",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requisicoes_saldo",
                to="gerente.fecho",
            ),
        ),
        migrations.AddField(
            model_name="requisicaosenhas",
            name="fecho",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requisicoes_senhas",
                to="gerente.fecho",
            ),
        ),
    ]
