# Generated by Django 5.2.4 on 2025-08-27 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gerente", "0017_fecho_movimento_fecho_requisicaosaldo_fecho_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="senha",
            options={
                "ordering": ["-data_criacao"],
                "verbose_name": "Senha",
                "verbose_name_plural": "Senhas",
            },
        ),
        migrations.AddField(
            model_name="senha",
            name="fecho",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="senhas_usadas",
                to="gerente.fecho",
            ),
        ),
    ]
