# Generated by Django 5.2.4 on 2025-08-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gerente", "0018_alter_senha_options_senha_fecho"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movimento",
            name="empresa",
        ),
    ]
