# Generated by Django 5.2.4 on 2025-08-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gerente", "0019_remove_movimento_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="senha",
            name="tipo_combustivel",
            field=models.CharField(
                blank=True,
                choices=[("gasolina", "Gasolina"), ("diesel", "Diesel")],
                help_text="Tipo de combustível selecionado no momento do uso da senha",
                max_length=10,
                null=True,
                verbose_name="Tipo de Combustível",
            ),
        ),
    ]
